CREATE DATABASE IF NOT EXISTS alloasso;
USE alloasso;
CREATE TABLE IF NOT EXISTS dons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    montant DECIMAL(10,2) NOT NULL,
    moyen VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);